# COCO 2017 dataset http://cocodataset.org - first 128 training images
# Train command: python train_v3.py --data usad_aod.yaml
# Default dataset location is next to YOLOv5:
#   /parent_folder
#     /coco128
#     /yolov5


# download command/URL (optional)
download: https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128.zip

# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: ../coco128/images/train2017/  # 128 images
val: ../coco128/images/train2017/  # 128 images

# number of classes
nc: 2

# class names
names: [ 'car','plane' ]
